# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/guidance_transforms',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/guidance_transforms',
                'lib_path': 'guidance_transforms'},
  'syms': {'guidance_transforms.core': {'guidance_transforms.core.foo': ('core.html#foo', 'guidance_transforms/core.py')}}}